services:
  authapi:
    image: davideshett/authapi:17.04.24.01 
    container_name: 'authapi'
    restart: always
    ports:
      - 4000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development